#!/bin/bash
#
################################################################################
#
# SCRIPT    ison
# AUTOR     pedro fernandes
# E-MAIL    pedrobfernandes37@gmail.com
# DATA      30-04-2021
#
################################################################################
#
# DESCRIÇÃO:
#
# Testa conectividade da máquina usando o ping nos vários pontos da rede,
# apontando se for o caso em que ponto da rede está o possível problema
# na conexão.
#
# PROCEDIMENTO:
#
# 1. ping loopback
# 2. ping gateway
# 3. ping ip na internet
# 4. ping nome de domínio na internet
#
################################################################################
#
# NOTAS:
#
# Variáveis DnsAddr e DomainTest, estão configuradas para dns e dominio google
# Para usar outros valores basta definir-los na linha de comando na chamada do
# script (ver abaixo).
# Da mesma forma, variável TimeOut refere-se ao parâmetro -w (deadline) do
# ping e está configurada por padrão para 5 segundos.
# Para mudar, novamente ver abaixo nos exemplos de uso.
#
################################################################################
#
# EXEMPLOS DE USO:
#
# 1. Usa valores padrão
#
#  $ ./ison
#
# 2. Muda os valores do dns e do dominio
#
#  $ DnsAddr=x.x.x.x DomainTest=www.xxxx.xxx.com ./ison
#
# 3. Muda valor apenas do dns
#
#  $ DnsAddr=x.x.x.x ./ison
#
# 4. Muda apenas o dominio
#
#  $ DomainTest=www.xxx.xxx.com ./ison
#
# 5. Especificar um deadline diferente
#
#  $ TimeOut=x ./ison
#
# 6.Pode mudar todos os parâmetros:
#
#  $ DnsAddr=x.x.x.x DomainTest=www.xxxxx.xxx.com TImeOut=x ./ison
#
################################################################################
#
# CHANGELOG:
#
# Script reescrito do zero com base em dicas de usuário do Site Viva o Linux,
# "https://www.vivaolinux.com.br"; usuário: msoliver (Marcelo Oliver),
# para ficar mais enxuto e um pouco "?" mais eficiente.
# Dicas postadas em comentário aqui:
# "https://www.vivaolinux.com.br/script/ison-testar-conectividade-da-maquina"
#
################################################################################
#
##### PARÂMETROS #####
#
TimeOut=${TimeOut:- 5}
Gateway=$(gawk '/^default/{print $3}' <<< $(ip r) || \
gawk '$4 == "UG" {print $2}' <<< $(route -n))
DnsAddr=${DnsAddr:-8.8.8.8}
DomainTest=${DomainTest:-'www.google.com'}
Targets="127.0.0.1 ${Gateway} ${DnsAddr} ${DomainTest}"
Success=0
Failure=0
#
#########################################################################
#
##### TESTES #####
#
clear

[ -z "$Gateway" ] && {

echo -e "\n\n*** Sem Conexão ***\n\n"
exit 0

}

for Target in $Targets
do
    echo Teste de Conectividade em: $Target
    #
    if ping -w $TimeOut $Target &> /dev/null
    then
        Success=$(( Success + 1 ))
        echo -e "\n\n*** Sucesso ***\n\n"
    else
        echo -e "\n\n*** Falha ***\n\n"
        Failure=$(( Failure + 1 ))
    fi
    #
    wait
done
#
################################################################################
#
Hit=$(bc <<< "scale=2; ($Success / 4) * 100")%;
Miss=$(bc <<< "scale=2; ($Failure / 4) * 100")%;

echo -e "\n\nTeste Concluído.\nAcertos: $Hit\nErros: $Miss\n"

exit 0
#
################################################################################
